backend:
    name: github
    repo: mctep/gatsby-netlify-web-site

media_folder: static/assets
public_folder: /assets

collections:
    - name: page
      label: Page
      folder: content/pages
      create: true
      fields:
        - {name: path, label: Path}
        - {name: welcome, label: "Welcome Message", widget:
            markdown}

